# Generated by Django 4.1.4 on 2023-04-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='abc',
        ),
    ]
