# Generated by Django 4.1.4 on 2023-04-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_abc_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
