# Generated by Django 4.1.4 on 2023-04-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_user_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
